name: Kickbase Market Alert (Discord)

on:
  workflow_dispatch:        # manuell startbar
  schedule:
    - cron: "*/15 * * * *"  # alle 15 Minuten

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Post test message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -sS -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\":\"✅ Workflow läuft!\"}" \
            "$DISCORD_WEBHOOK"
